theme: jekyll-theme-cayman
title: Jail Manager
description: The home of JailMan
show_downloads: true
github:
  zip_url: https://github.com/jailmanager/jailman/zipball/master
  tar_url: https://github.com/jailmanager/jailman/tarball/master